export const OPEN_DASHBOARD = "OPEN_DASHBOARD";
export const CLOSE_DASHBOARD = "CLOSE_DASHBOARD";
export const SHOW_HELPMODAL = "SHOW_HELPMODAL";
export const CLOSE_HELPMODAL = "CLOSE_HELPMODAL";
export const FETCH_GAME_DETAILS = "FETCH_GAME_DETAILS";
export const UPDATE_PLAYER_POSITION = "UPDATE_PLAYER_POSITION";
export const FETCH_USER_PLAYER = "FETCH_USER_PLAYER";
export const LOADING = "LOADING";
export const UPDATE_PLAYER_TURN_RESULTS = "UPDATE_PLAYER_TURN_RESULTS";
export const ROLL_DIE = "ROLL_DIE";
export const FINISH_AI_TURN = "FINISH_AI_TURN";
export const FINISH_USER_TURN = "FINISH_USER_TURN";
export const UPDATE_PLAYER_MAIL_CARDS = "UPDATE_PLAYER_MAIL_CARDS";
export const UPDATE_PLAYER_OPPOURTUNITY_CARDS = "UPDATE_PLAYER_OPPOURTUNITY_CARDS";
export const UPDATE_PLAYER_MONEY = "UPDATE_PLAYER_MONEY";
export const UPDATE_PLAYER_DAY = "UPDATE_PLAYER_DAY";

export const DISMISS_TURN_NOTIFICATION = "DISMISS_TURN_NOTIFICATION";
export const ANIMATE_PLAYER_MOVEMENT = "ANIMATE_PLAYER_MOVEMENT";
export const STOP_ANIMATING_PLAYER_MOVEMENT = "STOP_ANIMATING_PLAYER_MOVEMENT";
export const SHOW_DRAWN_CARD = "SHOW_DRAWN_CARD";
export const DISMISS_CARD_MODAL = "DISMISS_CARD_MODAL";
export const SHOW_DRAWN_OPPOURTUNITY_CARD = "SHOW_DRAWN_OPPOURTUNITY_CARD";
export const SHOW_TURN_NOTIFCATION = "SHOW_TURN_NOTIFCATION";

export const SHOW_LOGIN = "SHOW_LOGIN";
export const SHOW_SIGNUP = "SHOW_SIGNUP";
export const LOGIN = "LOGIN";

export const AUTHENTICATE = "AUTHENTICATE";

export const SET_USER_USERNAME = "SET_USER_USERNAME";
export const UPDATE_CURRENT_USER_TURN_RESULT = "UPDATE_CURRENT_USER_TURN_RESULT";
export const UPDATE_AI_TURN_RESULTS = "UPDATE_AI_TURN_RESULTS";

export const SET_SET_BACK_ROTATION_FLAG = "SET_SET_BACK_ROTATION_FLAG";

export const END_TURN = "END_TURN";
export const FLAG_AS_SET_BACK = "FLAG_AS_SET_BACK";
